Fix unused debug counter warning with GCC 16 (#120)
GCC 16 rejects non-debug builds with:

error: variable 'pieces_sent' set but not used
[-Werror=unused-but-set-variable=]